services:
  mysql:
    image: mysql:8.0
    container_name: travel_budget_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: travel_budget_app
    env_file: .env
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL-AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      EXCHANGE_RATE_API_KEY: ${EXCHANGE_RATE_API_KEY}
      UNSPLASH_API_KEY: ${UNSPLASH_API_KEY}
      SHOW_EXCEPTIONS: ${SHOW_EXCEPTIONS}
    ports:
      - "8080:8080"
    restart: unless-stopped

  app-dev:
    profiles:
      - development
    image: maven:3.9-eclipse-temurin-21
    container_name: travel_budget_app_dev
    working_dir: /app
    volumes:
      - .:/app
    command: ./mvnw spring-boot:run
    env_file: .env.development
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL-AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      EXCHANGE_RATE_API_KEY: ${EXCHANGE_RATE_API_KEY}
      UNSPLASH_API_KEY: ${UNSPLASH_API_KEY}
      SHOW_EXCEPTIONS: ${SHOW_EXCEPTIONS}
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
